<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ScrcpySeamless.Core/ScrcpySeamless.Core.csproj" />
    <ProjectReference Include="../ScrcpySeamless.Infrastructure/ScrcpySeamless.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources/Options/GeneratedOptionResources.en.json">
      <WithCulture>false</WithCulture>
      <LogicalName>ScrcpySeamless.Desktop.Resources.Options.GeneratedOptionResources.en.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
