// DO NOT EDIT - generated from spec/options/options.yaml by SpecGen v1.
#nullable enable
using System.Collections.ObjectModel;

namespace ScrcpySeamless.Core.Options;

public enum OptionClassification { Editable, Managed, Action, Unsupported, Alias, NativeOnly }
public enum OptionArgumentShape { None, Required, Optional }
public enum OptionValueKind { Boolean, String, Integer, UnsignedInteger, Decimal, Enum, Bitrate, Size, Duration, Color, Custom }

public sealed record OptionDescriptor
{
    public required string Id { get; init; }
    public string? LongName { get; init; }
    public char? ShortName { get; init; }
    public IReadOnlyList<string> Aliases { get; init; } = [];
    public string? AliasFor { get; init; }
    public required OptionClassification Classification { get; init; }
    public required OptionArgumentShape ArgumentShape { get; init; }
    public string? ArgumentHint { get; init; }
    public required OptionValueKind ValueKind { get; init; }
    public IReadOnlyList<string> EnumValues { get; init; } = [];
    public string? DefaultValue { get; init; }
    public decimal? Minimum { get; init; }
    public decimal? Maximum { get; init; }
    public string? Pattern { get; init; }
    public IReadOnlyList<string> Requires { get; init; } = [];
    public IReadOnlyList<string> Conflicts { get; init; } = [];
    public IReadOnlyList<string> RuleIds { get; init; } = [];
    public required string Category { get; init; }
    public required string LabelResourceKey { get; init; }
    public required string DescriptionResourceKey { get; init; }
    public string? BuildCapability { get; init; }
}

/// <summary>Generated static option descriptors; native runtime capabilities remain authoritative.</summary>
public static class GeneratedOptionCatalog
{
    public static IReadOnlyList<OptionDescriptor> All { get; } = Array.AsReadOnly(new OptionDescriptor[]
    {
        new OptionDescriptor
        {
            Id = "always-on-top",
            LongName = "always-on-top",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.always-on-top.label",
            DescriptionResourceKey = "options.always-on-top.description",
        },
        new OptionDescriptor
        {
            Id = "angle",
            LongName = "angle",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "degrees",
            ValueKind = OptionValueKind.Decimal,
            EnumValues = [],
            Pattern = "^-?\\d\u002B(\\.\\d\u002B)?$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.angle.label",
            DescriptionResourceKey = "options.angle.description",
        },
        new OptionDescriptor
        {
            Id = "audio-bit-rate",
            LongName = "audio-bit-rate",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.Bitrate,
            EnumValues = [],
            DefaultValue = "0",
            Minimum = 0m,
            Maximum = 2147483647m,
            Pattern = "^\\d\u002B[KMkm]?$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Audio",
            LabelResourceKey = "options.audio-bit-rate.label",
            DescriptionResourceKey = "options.audio-bit-rate.description",
        },
        new OptionDescriptor
        {
            Id = "audio-buffer",
            LongName = "audio-buffer",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "ms",
            ValueKind = OptionValueKind.UnsignedInteger,
            EnumValues = [],
            Minimum = 0m,
            Maximum = 3600000m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Audio",
            LabelResourceKey = "options.audio-buffer.label",
            DescriptionResourceKey = "options.audio-buffer.description",
        },
        new OptionDescriptor
        {
            Id = "audio-codec",
            LongName = "audio-codec",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "name",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["opus", "aac", "flac", "raw"],
            DefaultValue = "opus",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Audio",
            LabelResourceKey = "options.audio-codec.label",
            DescriptionResourceKey = "options.audio-codec.description",
        },
        new OptionDescriptor
        {
            Id = "audio-codec-options",
            LongName = "audio-codec-options",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "key[:type]=value[,...]",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Audio",
            LabelResourceKey = "options.audio-codec-options.label",
            DescriptionResourceKey = "options.audio-codec-options.description",
        },
        new OptionDescriptor
        {
            Id = "audio-dup",
            LongName = "audio-dup",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["audio-dup-requires-playback"],
            Category = "Audio",
            LabelResourceKey = "options.audio-dup.label",
            DescriptionResourceKey = "options.audio-dup.description",
        },
        new OptionDescriptor
        {
            Id = "audio-encoder",
            LongName = "audio-encoder",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "name",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Audio",
            LabelResourceKey = "options.audio-encoder.label",
            DescriptionResourceKey = "options.audio-encoder.description",
        },
        new OptionDescriptor
        {
            Id = "audio-source",
            LongName = "audio-source",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "source",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["output", "playback", "mic", "mic-unprocessed", "mic-camcorder", "mic-voice-recognition", "mic-voice-communication", "voice-call", "voice-call-uplink", "voice-call-downlink", "voice-performance"],
            Requires = [],
            Conflicts = [],
            RuleIds = ["audio-dup-requires-playback"],
            Category = "Audio",
            LabelResourceKey = "options.audio-source.label",
            DescriptionResourceKey = "options.audio-source.description",
        },
        new OptionDescriptor
        {
            Id = "audio-output-buffer",
            LongName = "audio-output-buffer",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "ms",
            ValueKind = OptionValueKind.UnsignedInteger,
            EnumValues = [],
            DefaultValue = "10",
            Minimum = 0m,
            Maximum = 1000m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Audio",
            LabelResourceKey = "options.audio-output-buffer.label",
            DescriptionResourceKey = "options.audio-output-buffer.description",
        },
        new OptionDescriptor
        {
            Id = "video-bit-rate",
            LongName = "video-bit-rate",
            ShortName = 'b',
            Aliases = ["-b"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.Bitrate,
            EnumValues = [],
            DefaultValue = "0",
            Minimum = 0m,
            Maximum = 2147483647m,
            Pattern = "^\\d\u002B[KMkm]?$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.video-bit-rate.label",
            DescriptionResourceKey = "options.video-bit-rate.description",
        },
        new OptionDescriptor
        {
            Id = "background-color",
            LongName = "background-color",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "hexcolor",
            ValueKind = OptionValueKind.Color,
            EnumValues = [],
            Pattern = "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.background-color.label",
            DescriptionResourceKey = "options.background-color.description",
        },
        new OptionDescriptor
        {
            Id = "camera-ar",
            LongName = "camera-ar",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "ar",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = ["camera-size"],
            RuleIds = ["camera-source-rules"],
            Category = "Camera",
            LabelResourceKey = "options.camera-ar.label",
            DescriptionResourceKey = "options.camera-ar.description",
        },
        new OptionDescriptor
        {
            Id = "camera-facing",
            LongName = "camera-facing",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "facing",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["front", "back", "external"],
            Requires = [],
            Conflicts = ["camera-id"],
            RuleIds = ["camera-source-rules"],
            Category = "Camera",
            LabelResourceKey = "options.camera-facing.label",
            DescriptionResourceKey = "options.camera-facing.description",
        },
        new OptionDescriptor
        {
            Id = "camera-fps",
            LongName = "camera-fps",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.UnsignedInteger,
            EnumValues = [],
            DefaultValue = "0",
            Minimum = 0m,
            Maximum = 65535m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = ["camera-source-rules"],
            Category = "Camera",
            LabelResourceKey = "options.camera-fps.label",
            DescriptionResourceKey = "options.camera-fps.description",
        },
        new OptionDescriptor
        {
            Id = "camera-high-speed",
            LongName = "camera-high-speed",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["camera-source-rules"],
            Category = "Camera",
            LabelResourceKey = "options.camera-high-speed.label",
            DescriptionResourceKey = "options.camera-high-speed.description",
        },
        new OptionDescriptor
        {
            Id = "camera-id",
            LongName = "camera-id",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "id",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = ["camera-facing"],
            RuleIds = ["camera-source-rules"],
            Category = "Camera",
            LabelResourceKey = "options.camera-id.label",
            DescriptionResourceKey = "options.camera-id.description",
        },
        new OptionDescriptor
        {
            Id = "camera-size",
            LongName = "camera-size",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "\u003Cwidth\u003Ex\u003Cheight\u003E",
            ValueKind = OptionValueKind.Size,
            EnumValues = [],
            Pattern = "^\\d\u002Bx\\d\u002B$",
            Requires = [],
            Conflicts = ["camera-ar"],
            RuleIds = ["camera-source-rules"],
            Category = "Camera",
            LabelResourceKey = "options.camera-size.label",
            DescriptionResourceKey = "options.camera-size.description",
        },
        new OptionDescriptor
        {
            Id = "camera-torch",
            LongName = "camera-torch",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Camera",
            LabelResourceKey = "options.camera-torch.label",
            DescriptionResourceKey = "options.camera-torch.description",
        },
        new OptionDescriptor
        {
            Id = "camera-zoom",
            LongName = "camera-zoom",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "zoom",
            ValueKind = OptionValueKind.Decimal,
            EnumValues = [],
            Pattern = "^\\d\u002B(\\.\\d\u002B)?$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Camera",
            LabelResourceKey = "options.camera-zoom.label",
            DescriptionResourceKey = "options.camera-zoom.description",
        },
        new OptionDescriptor
        {
            Id = "capture-orientation",
            LongName = "capture-orientation",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.capture-orientation.label",
            DescriptionResourceKey = "options.capture-orientation.description",
        },
        new OptionDescriptor
        {
            Id = "crop",
            LongName = "crop",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "width:height:x:y",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.crop.label",
            DescriptionResourceKey = "options.crop.description",
        },
        new OptionDescriptor
        {
            Id = "select-usb",
            LongName = "select-usb",
            ShortName = 'd',
            Aliases = ["-d"],
            Classification = OptionClassification.Managed,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.select-usb.label",
            DescriptionResourceKey = "options.select-usb.description",
        },
        new OptionDescriptor
        {
            Id = "disable-screensaver",
            LongName = "disable-screensaver",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.disable-screensaver.label",
            DescriptionResourceKey = "options.disable-screensaver.description",
        },
        new OptionDescriptor
        {
            Id = "display-id",
            LongName = "display-id",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "id",
            ValueKind = OptionValueKind.UnsignedInteger,
            EnumValues = [],
            DefaultValue = "0",
            Minimum = 0m,
            Maximum = 2147483647m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = ["virtual-display-rules"],
            Category = "Device",
            LabelResourceKey = "options.display-id.label",
            DescriptionResourceKey = "options.display-id.description",
        },
        new OptionDescriptor
        {
            Id = "display-ime-policy",
            LongName = "display-ime-policy",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["local", "fallback", "hide"],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.display-ime-policy.label",
            DescriptionResourceKey = "options.display-ime-policy.description",
        },
        new OptionDescriptor
        {
            Id = "display-orientation",
            LongName = "display-orientation",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["0", "90", "180", "270", "flip0", "flip90", "flip180", "flip270"],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.display-orientation.label",
            DescriptionResourceKey = "options.display-orientation.description",
        },
        new OptionDescriptor
        {
            Id = "select-tcpip",
            LongName = "select-tcpip",
            ShortName = 'e',
            Aliases = ["-e"],
            Classification = OptionClassification.Managed,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.select-tcpip.label",
            DescriptionResourceKey = "options.select-tcpip.description",
        },
        new OptionDescriptor
        {
            Id = "fullscreen",
            LongName = "fullscreen",
            ShortName = 'f',
            Aliases = ["-f"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.fullscreen.label",
            DescriptionResourceKey = "options.fullscreen.description",
        },
        new OptionDescriptor
        {
            Id = "force-adb-forward",
            LongName = "force-adb-forward",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.force-adb-forward.label",
            DescriptionResourceKey = "options.force-adb-forward.description",
        },
        new OptionDescriptor
        {
            Id = "gamepad-uhid-shortcut",
            ShortName = 'G',
            Aliases = ["-G"],
            AliasFor = "gamepad",
            Classification = OptionClassification.Alias,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.gamepad-uhid-shortcut.label",
            DescriptionResourceKey = "options.gamepad-uhid-shortcut.description",
        },
        new OptionDescriptor
        {
            Id = "gamepad",
            LongName = "gamepad",
            Aliases = ["-G"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "mode",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["disabled", "uhid", "aoa"],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.gamepad.label",
            DescriptionResourceKey = "options.gamepad.description",
        },
        new OptionDescriptor
        {
            Id = "help",
            LongName = "help",
            ShortName = 'h',
            Aliases = ["-h"],
            Classification = OptionClassification.Action,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.help.label",
            DescriptionResourceKey = "options.help.description",
        },
        new OptionDescriptor
        {
            Id = "keyboard-uhid-shortcut",
            ShortName = 'K',
            Aliases = ["-K"],
            AliasFor = "keyboard",
            Classification = OptionClassification.Alias,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.keyboard-uhid-shortcut.label",
            DescriptionResourceKey = "options.keyboard-uhid-shortcut.description",
        },
        new OptionDescriptor
        {
            Id = "keep-active",
            LongName = "keep-active",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.keep-active.label",
            DescriptionResourceKey = "options.keep-active.description",
        },
        new OptionDescriptor
        {
            Id = "keyboard",
            LongName = "keyboard",
            Aliases = ["-K"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "mode",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["disabled", "sdk", "uhid", "aoa"],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.keyboard.label",
            DescriptionResourceKey = "options.keyboard.description",
        },
        new OptionDescriptor
        {
            Id = "kill-adb-on-close",
            LongName = "kill-adb-on-close",
            Aliases = [],
            Classification = OptionClassification.Managed,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.kill-adb-on-close.label",
            DescriptionResourceKey = "options.kill-adb-on-close.description",
        },
        new OptionDescriptor
        {
            Id = "legacy-paste",
            LongName = "legacy-paste",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.legacy-paste.label",
            DescriptionResourceKey = "options.legacy-paste.description",
        },
        new OptionDescriptor
        {
            Id = "list-apps",
            LongName = "list-apps",
            Aliases = [],
            Classification = OptionClassification.Action,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.list-apps.label",
            DescriptionResourceKey = "options.list-apps.description",
        },
        new OptionDescriptor
        {
            Id = "list-cameras",
            LongName = "list-cameras",
            Aliases = [],
            Classification = OptionClassification.Action,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.list-cameras.label",
            DescriptionResourceKey = "options.list-cameras.description",
        },
        new OptionDescriptor
        {
            Id = "list-camera-sizes",
            LongName = "list-camera-sizes",
            Aliases = [],
            Classification = OptionClassification.Action,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.list-camera-sizes.label",
            DescriptionResourceKey = "options.list-camera-sizes.description",
        },
        new OptionDescriptor
        {
            Id = "list-displays",
            LongName = "list-displays",
            Aliases = [],
            Classification = OptionClassification.Action,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.list-displays.label",
            DescriptionResourceKey = "options.list-displays.description",
        },
        new OptionDescriptor
        {
            Id = "list-encoders",
            LongName = "list-encoders",
            Aliases = [],
            Classification = OptionClassification.Action,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.list-encoders.label",
            DescriptionResourceKey = "options.list-encoders.description",
        },
        new OptionDescriptor
        {
            Id = "max-size",
            LongName = "max-size",
            ShortName = 'm',
            Aliases = ["-m"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.UnsignedInteger,
            EnumValues = [],
            DefaultValue = "0",
            Minimum = 0m,
            Maximum = 65535m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.max-size.label",
            DescriptionResourceKey = "options.max-size.description",
        },
        new OptionDescriptor
        {
            Id = "mouse-uhid-shortcut",
            ShortName = 'M',
            Aliases = ["-M"],
            AliasFor = "mouse",
            Classification = OptionClassification.Alias,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.mouse-uhid-shortcut.label",
            DescriptionResourceKey = "options.mouse-uhid-shortcut.description",
        },
        new OptionDescriptor
        {
            Id = "max-fps",
            LongName = "max-fps",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Pattern = "^\\d\u002B(\\.\\d\u002B)?$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.max-fps.label",
            DescriptionResourceKey = "options.max-fps.description",
        },
        new OptionDescriptor
        {
            Id = "min-size-alignment",
            LongName = "min-size-alignment",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "alignment",
            ValueKind = OptionValueKind.UnsignedInteger,
            EnumValues = [],
            DefaultValue = "1",
            Minimum = 1m,
            Maximum = 16m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = ["min-size-alignment-power-of-two"],
            Category = "Video",
            LabelResourceKey = "options.min-size-alignment.label",
            DescriptionResourceKey = "options.min-size-alignment.description",
        },
        new OptionDescriptor
        {
            Id = "mouse",
            LongName = "mouse",
            Aliases = ["-M"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "mode",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["disabled", "sdk", "uhid", "aoa"],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.mouse.label",
            DescriptionResourceKey = "options.mouse.description",
        },
        new OptionDescriptor
        {
            Id = "mouse-bind",
            LongName = "mouse-bind",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "xxxx[:xxxx]",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.mouse-bind.label",
            DescriptionResourceKey = "options.mouse-bind.description",
        },
        new OptionDescriptor
        {
            Id = "no-control",
            LongName = "no-control",
            ShortName = 'n',
            Aliases = ["-n"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["session-output-required"],
            Category = "Control",
            LabelResourceKey = "options.no-control.label",
            DescriptionResourceKey = "options.no-control.description",
        },
        new OptionDescriptor
        {
            Id = "no-playback",
            LongName = "no-playback",
            ShortName = 'N',
            Aliases = ["-N"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["recording-output-semantics"],
            Category = "Video",
            LabelResourceKey = "options.no-playback.label",
            DescriptionResourceKey = "options.no-playback.description",
        },
        new OptionDescriptor
        {
            Id = "new-display",
            LongName = "new-display",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Optional,
            ArgumentHint = "[\u003Cwidth\u003Ex\u003Cheight\u003E][/\u003Cdpi\u003E]",
            ValueKind = OptionValueKind.Size,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["virtual-display-rules"],
            Category = "Device",
            LabelResourceKey = "options.new-display.label",
            DescriptionResourceKey = "options.new-display.description",
        },
        new OptionDescriptor
        {
            Id = "no-audio",
            LongName = "no-audio",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["recording-output-semantics", "session-output-required"],
            Category = "Audio",
            LabelResourceKey = "options.no-audio.label",
            DescriptionResourceKey = "options.no-audio.description",
        },
        new OptionDescriptor
        {
            Id = "no-audio-playback",
            LongName = "no-audio-playback",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["recording-output-semantics"],
            Category = "Audio",
            LabelResourceKey = "options.no-audio-playback.label",
            DescriptionResourceKey = "options.no-audio-playback.description",
        },
        new OptionDescriptor
        {
            Id = "no-cleanup",
            LongName = "no-cleanup",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.no-cleanup.label",
            DescriptionResourceKey = "options.no-cleanup.description",
        },
        new OptionDescriptor
        {
            Id = "no-clipboard-autosync",
            LongName = "no-clipboard-autosync",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.no-clipboard-autosync.label",
            DescriptionResourceKey = "options.no-clipboard-autosync.description",
        },
        new OptionDescriptor
        {
            Id = "no-downsize-on-error",
            LongName = "no-downsize-on-error",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.no-downsize-on-error.label",
            DescriptionResourceKey = "options.no-downsize-on-error.description",
        },
        new OptionDescriptor
        {
            Id = "no-key-repeat",
            LongName = "no-key-repeat",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.no-key-repeat.label",
            DescriptionResourceKey = "options.no-key-repeat.description",
        },
        new OptionDescriptor
        {
            Id = "no-mipmaps",
            LongName = "no-mipmaps",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.no-mipmaps.label",
            DescriptionResourceKey = "options.no-mipmaps.description",
        },
        new OptionDescriptor
        {
            Id = "no-mouse-hover",
            LongName = "no-mouse-hover",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.no-mouse-hover.label",
            DescriptionResourceKey = "options.no-mouse-hover.description",
        },
        new OptionDescriptor
        {
            Id = "no-power-on",
            LongName = "no-power-on",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.no-power-on.label",
            DescriptionResourceKey = "options.no-power-on.description",
        },
        new OptionDescriptor
        {
            Id = "no-vd-destroy-content",
            LongName = "no-vd-destroy-content",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.no-vd-destroy-content.label",
            DescriptionResourceKey = "options.no-vd-destroy-content.description",
        },
        new OptionDescriptor
        {
            Id = "no-vd-system-decorations",
            LongName = "no-vd-system-decorations",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.no-vd-system-decorations.label",
            DescriptionResourceKey = "options.no-vd-system-decorations.description",
        },
        new OptionDescriptor
        {
            Id = "no-video",
            LongName = "no-video",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["recording-output-semantics", "session-output-required"],
            Category = "Video",
            LabelResourceKey = "options.no-video.label",
            DescriptionResourceKey = "options.no-video.description",
        },
        new OptionDescriptor
        {
            Id = "no-video-playback",
            LongName = "no-video-playback",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["recording-output-semantics"],
            Category = "Video",
            LabelResourceKey = "options.no-video-playback.label",
            DescriptionResourceKey = "options.no-video-playback.description",
        },
        new OptionDescriptor
        {
            Id = "no-window",
            LongName = "no-window",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["recording-output-semantics"],
            Category = "Video",
            LabelResourceKey = "options.no-window.label",
            DescriptionResourceKey = "options.no-window.description",
        },
        new OptionDescriptor
        {
            Id = "no-window-aspect-ratio-lock",
            LongName = "no-window-aspect-ratio-lock",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.no-window-aspect-ratio-lock.label",
            DescriptionResourceKey = "options.no-window-aspect-ratio-lock.description",
        },
        new OptionDescriptor
        {
            Id = "orientation",
            LongName = "orientation",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["0", "90", "180", "270"],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.orientation.label",
            DescriptionResourceKey = "options.orientation.description",
        },
        new OptionDescriptor
        {
            Id = "otg",
            LongName = "otg",
            Aliases = [],
            Classification = OptionClassification.Unsupported,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.otg.label",
            DescriptionResourceKey = "options.otg.description",
            BuildCapability = "libusb-aoa",
        },
        new OptionDescriptor
        {
            Id = "port",
            LongName = "port",
            ShortName = 'p',
            Aliases = ["-p"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "port[:port]",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Pattern = "^\\d\u002B(:\\d\u002B)?$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.port.label",
            DescriptionResourceKey = "options.port.description",
        },
        new OptionDescriptor
        {
            Id = "pause-on-exit",
            LongName = "pause-on-exit",
            Aliases = [],
            Classification = OptionClassification.Managed,
            ArgumentShape = OptionArgumentShape.Optional,
            ArgumentHint = "mode",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["true", "false", "if-error"],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.pause-on-exit.label",
            DescriptionResourceKey = "options.pause-on-exit.description",
        },
        new OptionDescriptor
        {
            Id = "power-off-on-close",
            LongName = "power-off-on-close",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.power-off-on-close.label",
            DescriptionResourceKey = "options.power-off-on-close.description",
        },
        new OptionDescriptor
        {
            Id = "prefer-text",
            LongName = "prefer-text",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.prefer-text.label",
            DescriptionResourceKey = "options.prefer-text.description",
        },
        new OptionDescriptor
        {
            Id = "print-fps",
            LongName = "print-fps",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.print-fps.label",
            DescriptionResourceKey = "options.print-fps.description",
        },
        new OptionDescriptor
        {
            Id = "push-target",
            LongName = "push-target",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "path",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.push-target.label",
            DescriptionResourceKey = "options.push-target.description",
        },
        new OptionDescriptor
        {
            Id = "record",
            LongName = "record",
            ShortName = 'r',
            Aliases = ["-r"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "file.mp4",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["recording-output-semantics"],
            Category = "Recording",
            LabelResourceKey = "options.record.label",
            DescriptionResourceKey = "options.record.description",
        },
        new OptionDescriptor
        {
            Id = "raw-key-events",
            LongName = "raw-key-events",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.raw-key-events.label",
            DescriptionResourceKey = "options.raw-key-events.description",
        },
        new OptionDescriptor
        {
            Id = "record-format",
            LongName = "record-format",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "format",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["mp4", "mkv", "m4a", "mka", "opus", "aac", "flac", "wav"],
            Requires = ["record"],
            Conflicts = [],
            RuleIds = [],
            Category = "Recording",
            LabelResourceKey = "options.record-format.label",
            DescriptionResourceKey = "options.record-format.description",
        },
        new OptionDescriptor
        {
            Id = "record-orientation",
            LongName = "record-orientation",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["0", "90", "180", "270"],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Recording",
            LabelResourceKey = "options.record-orientation.label",
            DescriptionResourceKey = "options.record-orientation.description",
        },
        new OptionDescriptor
        {
            Id = "render-driver",
            LongName = "render-driver",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "name",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.render-driver.label",
            DescriptionResourceKey = "options.render-driver.description",
        },
        new OptionDescriptor
        {
            Id = "render-fit",
            LongName = "render-fit",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "mode",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["letterbox", "stretched", "unscaled"],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.render-fit.label",
            DescriptionResourceKey = "options.render-fit.description",
        },
        new OptionDescriptor
        {
            Id = "require-audio",
            LongName = "require-audio",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Audio",
            LabelResourceKey = "options.require-audio.label",
            DescriptionResourceKey = "options.require-audio.description",
        },
        new OptionDescriptor
        {
            Id = "serial",
            LongName = "serial",
            ShortName = 's',
            Aliases = ["-s"],
            Classification = OptionClassification.Managed,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "serial",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.serial.label",
            DescriptionResourceKey = "options.serial.description",
        },
        new OptionDescriptor
        {
            Id = "turn-screen-off",
            LongName = "turn-screen-off",
            ShortName = 'S',
            Aliases = ["-S"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.turn-screen-off.label",
            DescriptionResourceKey = "options.turn-screen-off.description",
        },
        new OptionDescriptor
        {
            Id = "screen-off-timeout",
            LongName = "screen-off-timeout",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "seconds",
            ValueKind = OptionValueKind.UnsignedInteger,
            EnumValues = [],
            Minimum = 0m,
            Maximum = 2147483m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.screen-off-timeout.label",
            DescriptionResourceKey = "options.screen-off-timeout.description",
        },
        new OptionDescriptor
        {
            Id = "shortcut-mod",
            LongName = "shortcut-mod",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "key[\u002B...][,...]",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Control",
            LabelResourceKey = "options.shortcut-mod.label",
            DescriptionResourceKey = "options.shortcut-mod.description",
        },
        new OptionDescriptor
        {
            Id = "start-app",
            LongName = "start-app",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "name",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.start-app.label",
            DescriptionResourceKey = "options.start-app.description",
        },
        new OptionDescriptor
        {
            Id = "show-touches",
            LongName = "show-touches",
            ShortName = 't',
            Aliases = ["-t"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.show-touches.label",
            DescriptionResourceKey = "options.show-touches.description",
        },
        new OptionDescriptor
        {
            Id = "tcpip",
            LongName = "tcpip",
            Aliases = [],
            Classification = OptionClassification.Managed,
            ArgumentShape = OptionArgumentShape.Optional,
            ArgumentHint = "[\u002B]ip[:port]",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.tcpip.label",
            DescriptionResourceKey = "options.tcpip.description",
        },
        new OptionDescriptor
        {
            Id = "time-limit",
            LongName = "time-limit",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "seconds",
            ValueKind = OptionValueKind.UnsignedInteger,
            EnumValues = [],
            DefaultValue = "0",
            Minimum = 0m,
            Maximum = 2147483647m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Recording",
            LabelResourceKey = "options.time-limit.label",
            DescriptionResourceKey = "options.time-limit.description",
        },
        new OptionDescriptor
        {
            Id = "tunnel-host",
            LongName = "tunnel-host",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "ip",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.tunnel-host.label",
            DescriptionResourceKey = "options.tunnel-host.description",
        },
        new OptionDescriptor
        {
            Id = "tunnel-port",
            LongName = "tunnel-port",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "port",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Minimum = 0m,
            Maximum = 65535m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.tunnel-port.label",
            DescriptionResourceKey = "options.tunnel-port.description",
        },
        new OptionDescriptor
        {
            Id = "version",
            LongName = "version",
            ShortName = 'v',
            Aliases = ["-v"],
            Classification = OptionClassification.Action,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.version.label",
            DescriptionResourceKey = "options.version.description",
        },
        new OptionDescriptor
        {
            Id = "verbosity",
            LongName = "verbosity",
            ShortName = 'V',
            Aliases = ["-V"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["verbose", "debug", "info", "warn", "error"],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.verbosity.label",
            DescriptionResourceKey = "options.verbosity.description",
        },
        new OptionDescriptor
        {
            Id = "v4l2-sink",
            LongName = "v4l2-sink",
            Aliases = [],
            Classification = OptionClassification.Unsupported,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "/dev/videoN",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.v4l2-sink.label",
            DescriptionResourceKey = "options.v4l2-sink.description",
            BuildCapability = "linux-v4l2",
        },
        new OptionDescriptor
        {
            Id = "v4l2-buffer",
            LongName = "v4l2-buffer",
            Aliases = [],
            Classification = OptionClassification.Unsupported,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "ms",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Technical",
            LabelResourceKey = "options.v4l2-buffer.label",
            DescriptionResourceKey = "options.v4l2-buffer.description",
            BuildCapability = "linux-v4l2",
        },
        new OptionDescriptor
        {
            Id = "video-buffer",
            LongName = "video-buffer",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "ms",
            ValueKind = OptionValueKind.UnsignedInteger,
            EnumValues = [],
            DefaultValue = "0",
            Minimum = 0m,
            Maximum = 3600000m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.video-buffer.label",
            DescriptionResourceKey = "options.video-buffer.description",
        },
        new OptionDescriptor
        {
            Id = "video-codec",
            LongName = "video-codec",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "name",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["h264", "h265", "av1"],
            DefaultValue = "h264",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.video-codec.label",
            DescriptionResourceKey = "options.video-codec.description",
        },
        new OptionDescriptor
        {
            Id = "video-codec-options",
            LongName = "video-codec-options",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "key[:type]=value[,...]",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.video-codec-options.label",
            DescriptionResourceKey = "options.video-codec-options.description",
        },
        new OptionDescriptor
        {
            Id = "video-encoder",
            LongName = "video-encoder",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "name",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Video",
            LabelResourceKey = "options.video-encoder.label",
            DescriptionResourceKey = "options.video-encoder.description",
        },
        new OptionDescriptor
        {
            Id = "video-source",
            LongName = "video-source",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "source",
            ValueKind = OptionValueKind.Enum,
            EnumValues = ["display", "camera"],
            DefaultValue = "display",
            Requires = [],
            Conflicts = [],
            RuleIds = ["camera-source-rules", "virtual-display-rules"],
            Category = "Video",
            LabelResourceKey = "options.video-source.label",
            DescriptionResourceKey = "options.video-source.description",
        },
        new OptionDescriptor
        {
            Id = "stay-awake",
            LongName = "stay-awake",
            ShortName = 'w',
            Aliases = ["-w"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Device",
            LabelResourceKey = "options.stay-awake.label",
            DescriptionResourceKey = "options.stay-awake.description",
        },
        new OptionDescriptor
        {
            Id = "window-borderless",
            LongName = "window-borderless",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.window-borderless.label",
            DescriptionResourceKey = "options.window-borderless.description",
        },
        new OptionDescriptor
        {
            Id = "window-title",
            LongName = "window-title",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "text",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.window-title.label",
            DescriptionResourceKey = "options.window-title.description",
        },
        new OptionDescriptor
        {
            Id = "window-x",
            LongName = "window-x",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Minimum = -32767m,
            Maximum = 32767m,
            Pattern = "^(auto|-?\\d\u002B)$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.window-x.label",
            DescriptionResourceKey = "options.window-x.description",
        },
        new OptionDescriptor
        {
            Id = "window-y",
            LongName = "window-y",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.String,
            EnumValues = [],
            Minimum = -32767m,
            Maximum = 32767m,
            Pattern = "^(auto|-?\\d\u002B)$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.window-y.label",
            DescriptionResourceKey = "options.window-y.description",
        },
        new OptionDescriptor
        {
            Id = "window-width",
            LongName = "window-width",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.UnsignedInteger,
            EnumValues = [],
            DefaultValue = "0",
            Minimum = 0m,
            Maximum = 65535m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.window-width.label",
            DescriptionResourceKey = "options.window-width.description",
        },
        new OptionDescriptor
        {
            Id = "window-height",
            LongName = "window-height",
            Aliases = [],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.Required,
            ArgumentHint = "value",
            ValueKind = OptionValueKind.UnsignedInteger,
            EnumValues = [],
            DefaultValue = "0",
            Minimum = 0m,
            Maximum = 65535m,
            Pattern = "^\\d\u002B$",
            Requires = [],
            Conflicts = [],
            RuleIds = [],
            Category = "Window",
            LabelResourceKey = "options.window-height.label",
            DescriptionResourceKey = "options.window-height.description",
        },
        new OptionDescriptor
        {
            Id = "flex-display",
            LongName = "flex-display",
            ShortName = 'x',
            Aliases = ["-x"],
            Classification = OptionClassification.Editable,
            ArgumentShape = OptionArgumentShape.None,
            ValueKind = OptionValueKind.Boolean,
            EnumValues = [],
            Requires = [],
            Conflicts = [],
            RuleIds = ["virtual-display-rules"],
            Category = "Device",
            LabelResourceKey = "options.flex-display.label",
            DescriptionResourceKey = "options.flex-display.description",
        },
    });
    private static readonly IReadOnlyDictionary<string, OptionDescriptor> ById =
        new ReadOnlyDictionary<string, OptionDescriptor>(All.ToDictionary(option => option.Id, StringComparer.Ordinal));

    public static bool TryGet(string optionId, out OptionDescriptor descriptor)
    {
        return ById.TryGetValue(optionId, out descriptor!);
    }
}
